### PR TITLE
Fixing computation of lda/ldb/ldc with cblas

### LINKED ISSUE #374: MHA forward fails with intel-mkl feature
This is related to incorrect strides for cblas sgemm. Related to #365 #362

### PR DESCRIPTION
**Pull request by coreylowman**
Resolves #374

### CODE REVIEW

File: src/tensor_ops/matmul/cpu_kernel.rs [hunk 1]
```diff
@@ -31,17 +31,36 @@ pub(crate) fn matmul<M: Dim, K: Dim, N: Dim>(
...
+            [1, ld] => (ld as i32, true),
+            _ => panic!("At least one of b's strides must be 1 for cblas"),
+        };
+
+        let (ldc, c_trans) = match c.strides {
+            [1, 0] => (m as i32, true),
+            [0, 1] => (n as i32, false),
+            [ld, 1] => (ld as i32, false),
+            [1, ld] => (ld as i32, true),
+            _ => panic!("At least one of b's strides must be 1 for cblas"),
```
Comment (coreylowman) [inline src/tensor_ops/matmul/cpu_kernel.rs:56]:
```suggestion
            _ => panic!("At least one of c's strides must be 1 for cblas"),
```
